server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost


spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

      routes:
        - id: tingeso2-m1
          uri: lb://tingeso2-m1
          predicates:
            - Path=/api/rate/**
        - id: Tingeso2_M2
          uri: lb://tingeso2_m2
          predicates:
            - Path=/api/groupD/**
        - id: Tingeso2_M3
          uri: lb://tingeso2_m3
          predicates:
            - Path=/api/fidelityD/**
        - id: Tingeso2_M4
          uri: lb://tingeso2_m4
          predicates:
            - Path=/api/specialD/**
        - id: Tingeso2_M5-receipt
          uri: lb://tingeso2_m5
          predicates:
            - Path=/api/receipt/**
        - id: Tingeso2_M5-reservation
          uri: lb://tingeso2_m5
          predicates:
            - Path=/api/reservation/**
        - id: Tingeso2_M6
          uri: lb://tingeso2_m6
          predicates:
            - Path=/api/rack/**
        - id: Tingeso2_M7
          uri: lb://tingeso2_m7
          predicates:
            - Path=/api/report/**
        - id: Tingeso2_M8
          uri: lb://tingeso2_m8
          predicates:
            - Path=/api/client/**
        