server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-service:8761/eureka
  instance:
    hostname: eureka-service


spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

      routes:
        - id: tingeso2-m1
          uri: lb://tingeso2-m1
          predicates:
            - Path=/api/rate/**
        - id: tingeso2-m2
          uri: lb://tingeso2-m2
          predicates:
            - Path=/api/groupD/**
        - id: tingeso2-m3
          uri: lb://tingeso2-m3
          predicates:
            - Path=/api/fidelityD/**
        - id: tingeso2-m4
          uri: lb://tingeso2-m4
          predicates:
            - Path=/api/specialD/**
        - id: tingeso2-m5-receipt
          uri: lb://tingeso2-m5
          predicates:
            - Path=/api/receipt/**
        - id: tingeso2-m5-reservation
          uri: lb://tingeso2-m5
          predicates:
            - Path=/api/reservation/**
        - id: tingeso2-m6
          uri: lb://tingeso2-m6
          predicates:
            - Path=/api/rack/**
        - id: tingeso2-m7
          uri: lb://tingeso2-m7
          predicates:
            - Path=/api/report/**
        - id: tingeso2-m8
          uri: lb://tingeso2-m8
          predicates:
            - Path=/api/client/**
        