server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-service:8761/eureka
  instance:
    hostname: eureka-service


spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

      routes:
        - id: rate-service
          uri: lb://rate-service
          predicates:
            - Path=/api/rate/**
        - id: gdiscount-service
          uri: lb://gdiscount-service
          predicates:
            - Path=/api/groupD/**
        - id: fdiscount-service
          uri: lb://fdiscount-service
          predicates:
            - Path=/api/fidelityD/**
        - id: sprate-spdiscount-service
          uri: lb://sprate-spdiscount-service
          predicates:
            - Path=/api/specialD/**
        - id: reservation-receipt-service1
          uri: lb://reservation-receipt-service
          predicates:
            - Path=/api/receipt/**
        - id: reservation-receipt-service2
          uri: lb://reservation-receipt-service
          predicates:
            - Path=/api/reservation/**
        - id: rack-service
          uri: lb://rack-service
          predicates:
            - Path=/api/rack/**
        - id: report-service
          uri: lb://report-service
          predicates:
            - Path=/api/report/**
        - id: client-service
          uri: lb://client-service
          predicates:
            - Path=/api/client/**
        