server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  application:
    name: tingeso2-m1
  cloud:
    discovery:
      eureka:
        client:
          service-url:
            defaultZone: http://eureka-service.default.svc.cluster.local:8761/eureka/
        instance:
          instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
